name: flutter_web_preloader_hooks

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mason: ^0.1.0-dev.50
  yaml: ^3.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
